### PR TITLE
feat(data): add credits data

### PR DESCRIPTION
**Pull request by davidmhatton**
Adds data for credits platform.

@alexei-led I took the most educated guess I could RE the tags, but if you feel they need to change feel free to flag.

### CODE REVIEW

**Comment by bkw** [comment]
So are we adding a whole new platform called credits? Shouldn't this be part of finance?

**Comment by taltultc** [comment]
> So are we adding a whole new platform called `credits`? Shouldn't this be part of finance?

Yes we are adding a credits platform

**Comment by bkw** [comment]
Afaik, we currently lack a process on the Zendesk side for this new platform. We at least need a group to route this to, that's why I asked about Finance. Is there any documentation about the envisioned process? Who is expected to handle these tickets?

**Comment by taltultc** [comment]
> Afaik, we currently lack a process on the Zendesk side for this new platform. We at least need a group to route this to, that's why I asked about Finance. Is there any documentation about the envisioned process? Who is expected to handle these tickets?

the tickets should be routed to Daniela Kortin. I'll see if there is any documentation

**Comment by bkw** [comment]
I creaded a group `Credits` in Zendesk and added Daniela as the only member.

**Pull request merged**
