### PR TITLE
feat: add marketplace services

### PR DESCRIPTION
**Pull request by taltultc**
add marketplace service to GCP/AWS

### CODE REVIEW

**Review by bkw — CHANGES_REQUESTED** [review]
The data files are generated from the output of aws.sh and gcp.sh, so your changes would be overwritten the next time we regenerate them.

A more sustainable way is to add these static addons with jq in aws.sh and gcp.sh, like demonstrated in #8 , so the new entries would be added each time the scripts are run.

**Comment by taltultc** [comment]
> The data files are generated from the output of aws.sh and gcp.sh, so your changes would be overwritten the next time we regenerate them.
> 
> A more sustainable way is to add these static addons with jq in aws.sh and gcp.sh, like demonstrated in #8 , so the new entries would be added each time the scripts are run.

done

**Review by bkw — APPROVED** [review]
Looks great!

**Comment by taltultc** [comment]
@alexei-led @bkw can we disable the signed commit?

**Pull request merged**
