### PR TITLE
feat(support): add OTHER option to CMP [CMP-7097]

### PR DESCRIPTION
**Pull request by doitbenjamin**
add OTHER option to CMP

## Related tasks:

-   [Include “Other” category for DoiT CMP Support Flow](https://doitintl.atlassian.net/browse/CMP-7097)

### CODE REVIEW

**Review by taltultc — APPROVED** [review]

**Review by taltultc — DISMISSED** [review]

**Review by taltultc — APPROVED** [review]

**Review by bkw — DISMISSED** [review]
cmp.json is not auto-generated, so adding stuff here is ok.

**Comment by bkw** [comment]
> @bkw any idea why I can't merge this PR? the merge button is disabled

@taltultc Turns out all commits need to be [signed](https://docs.github.com/articles/about-gpg/), not sure who enabled that, @alexei-led ?

**Review by bkw — APPROVED** [review]
LGTM

**Comment by bkw** [comment]
@taltultc done.

**Pull request merged**
