### PR TITLE
feat(other): add other

### PR DESCRIPTION
**Pull request by taltultc**

### CODE REVIEW

**Comment by bkw** [comment]
This PR operates on the json files that are the output of the scraping script. These changes would be erased the next time the scripts are run and their output is checked in again.

So in order add an `other` category, you'd have to add this as a preprocessing stage of [aws.sh](../blob/master/aws.sh) and [gcp.sh](../blob/master/gcp.sh).

That being said, wether we _want_ an `other` category, is a whole different discussion, though.

**Review by alexei-led — CHANGES_REQUESTED** [review]
too many changes. can we skip reformating JSON?
better to update sh files that scrap AWS/GCP page

**Comment by taltultc** [comment]
@alexei-led @bkw we need to add other to each category, would it be possible for you to take care of it?
for example storage category: 
image

**Comment by taltultc** [comment]
> @alexei-led @bkw we need to add other to each category, would it be possible for you to take care of it? for example storage category: 

I'll do it on the client so we don't have to add anything else

**Comment by bkw** [comment]
> I'll do it on the client so we don't have to add anything else

Please don't do that. We rely on a single source of truth for this data for other workflows and processes as well, [ZenCat](https://github.com/doitintl/zen-cat) for example.

I'll try to help with the PR.

**Pull request closed without merging**
